sudo: false

language: java

jdk:
  - openjdk8
  - openjdk11

before_install:
  # Travis sets this and it causes issues with workers.
  - unset _JAVA_OPTIONS
  # Not actually used since we aren't building/testing the Android version, but
  # Maven still needs an absolute path or it complains.
  - export ANDROID_HOME=/

install: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install -U -DskipTests=true -am -pl caliper

script: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify -U -Dmaven.javadoc.skip=true -am -pl caliper

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master
    - /^release.*$/
