sudo: false

language: java

jdk:
  - oraclejdk8

install: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn install -U -DskipTests=true -am -pl caliper

script: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn verify -U -Dmaven.javadoc.skip=true -am -pl caliper

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master
    - /^release.*$/
