sudo: false

language: java

jdk:
  - oraclejdk8

install: mvn -B install -U -DskipTests=true

script: mvn -B verify -U -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master
    - /^release.*$/
